---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: #{AGENT-NAMESPACE}
data:
  MQ_ADDR: #{MQ_ADDR}
  MQ_USER: #{MQ_USER}
  MQ_PASSWORD: #{MQ_PASSWORD}
  CLUSTER_ID: #{CLUSTER_ID}
  AGENT_SCOPE: #{AGENT-SCOPE}
  VERSION: #{VERSION}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: #{AGENT-NAMESPACE}
  labels:
    app: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      serviceAccountName: #{SUBSCRIBER-SERVICE-ACCOUNT}
      #{nodeselector}
      containers:
        - name: subscriber
          image: imrajdas/subscriber:ci
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: agent-config
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace